spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workkits?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

logging:
  level:
    me.yummykang: DEBUG
    org.jooq: DEBUG
    org.springframework: DEBUG

jwt:
  secret: demon
  expiration: 3600
  header: Authorization
  tokenHead: "Bearer "

intercept_url:
  excludes: "/auth/login"


