/*
 * This file is generated by jOOQ.
*/
package me.yummykang.entity.tables;


import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.yummykang.entity.Keys;
import me.yummykang.entity.Workkits;
import me.yummykang.entity.tables.records.CheckInRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckIn extends TableImpl<CheckInRecord> {

    private static final long serialVersionUID = -588753391;

    /**
     * The reference instance of <code>workkits.check_in</code>
     */
    public static final CheckIn CHECK_IN = new CheckIn();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CheckInRecord> getRecordType() {
        return CheckInRecord.class;
    }

    /**
     * The column <code>workkits.check_in.id</code>.
     */
    public final TableField<CheckInRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>workkits.check_in.check_in_time</code>.
     */
    public final TableField<CheckInRecord, Date> CHECK_IN_TIME = createField("check_in_time", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>workkits.check_in.check_out_time</code>.
     */
    public final TableField<CheckInRecord, Date> CHECK_OUT_TIME = createField("check_out_time", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * The column <code>workkits.check_in.left_time</code>.
     */
    public final TableField<CheckInRecord, Integer> LEFT_TIME = createField("left_time", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>workkits.check_in</code> table reference
     */
    public CheckIn() {
        this("check_in", null);
    }

    /**
     * Create an aliased <code>workkits.check_in</code> table reference
     */
    public CheckIn(String alias) {
        this(alias, CHECK_IN);
    }

    private CheckIn(String alias, Table<CheckInRecord> aliased) {
        this(alias, aliased, null);
    }

    private CheckIn(String alias, Table<CheckInRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Workkits.WORKKITS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CheckInRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CHECK_IN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CheckInRecord> getPrimaryKey() {
        return Keys.KEY_CHECK_IN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CheckInRecord>> getKeys() {
        return Arrays.<UniqueKey<CheckInRecord>>asList(Keys.KEY_CHECK_IN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CheckIn as(String alias) {
        return new CheckIn(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CheckIn rename(String name) {
        return new CheckIn(name, null);
    }
}
