/*
 * This file is generated by jOOQ.
*/
package me.yummykang.entity.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CheckIn implements Serializable {

    private static final long serialVersionUID = -955556274;

    private Integer id;
    private Date    checkInTime;
    private Date    checkOutTime;
    private Integer leftTime;

    public CheckIn() {}

    public CheckIn(CheckIn value) {
        this.id = value.id;
        this.checkInTime = value.checkInTime;
        this.checkOutTime = value.checkOutTime;
        this.leftTime = value.leftTime;
    }

    public CheckIn(
        Integer id,
        Date    checkInTime,
        Date    checkOutTime,
        Integer leftTime
    ) {
        this.id = id;
        this.checkInTime = checkInTime;
        this.checkOutTime = checkOutTime;
        this.leftTime = leftTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getCheckInTime() {
        return this.checkInTime;
    }

    public void setCheckInTime(Date checkInTime) {
        this.checkInTime = checkInTime;
    }

    public Date getCheckOutTime() {
        return this.checkOutTime;
    }

    public void setCheckOutTime(Date checkOutTime) {
        this.checkOutTime = checkOutTime;
    }

    public Integer getLeftTime() {
        return this.leftTime;
    }

    public void setLeftTime(Integer leftTime) {
        this.leftTime = leftTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CheckIn (");

        sb.append(id);
        sb.append(", ").append(checkInTime);
        sb.append(", ").append(checkOutTime);
        sb.append(", ").append(leftTime);

        sb.append(")");
        return sb.toString();
    }
}
