/*
 * This file is generated by jOOQ.
*/
package me.yummykang.entity.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OauthAccessToken implements Serializable {

    private static final long serialVersionUID = 1748032123;

    private String tokenId;
    private byte[] token;
    private String authenticationId;
    private String userName;
    private String clientId;
    private byte[] authentication;
    private String refreshToken;

    public OauthAccessToken() {}

    public OauthAccessToken(OauthAccessToken value) {
        this.tokenId = value.tokenId;
        this.token = value.token;
        this.authenticationId = value.authenticationId;
        this.userName = value.userName;
        this.clientId = value.clientId;
        this.authentication = value.authentication;
        this.refreshToken = value.refreshToken;
    }

    public OauthAccessToken(
        String tokenId,
        byte[] token,
        String authenticationId,
        String userName,
        String clientId,
        byte[] authentication,
        String refreshToken
    ) {
        this.tokenId = tokenId;
        this.token = token;
        this.authenticationId = authenticationId;
        this.userName = userName;
        this.clientId = clientId;
        this.authentication = authentication;
        this.refreshToken = refreshToken;
    }

    public String getTokenId() {
        return this.tokenId;
    }

    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

    public byte[] getToken() {
        return this.token;
    }

    public void setToken(byte... token) {
        this.token = token;
    }

    public String getAuthenticationId() {
        return this.authenticationId;
    }

    public void setAuthenticationId(String authenticationId) {
        this.authenticationId = authenticationId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getClientId() {
        return this.clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public byte[] getAuthentication() {
        return this.authentication;
    }

    public void setAuthentication(byte... authentication) {
        this.authentication = authentication;
    }

    public String getRefreshToken() {
        return this.refreshToken;
    }

    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OauthAccessToken (");

        sb.append(tokenId);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(authenticationId);
        sb.append(", ").append(userName);
        sb.append(", ").append(clientId);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(refreshToken);

        sb.append(")");
        return sb.toString();
    }
}
