/*
 * This file is generated by jOOQ.
*/
package me.yummykang.entity;


import javax.annotation.Generated;

import me.yummykang.entity.tables.CheckIn;
import me.yummykang.entity.tables.OauthAccessToken;
import me.yummykang.entity.tables.OauthClientDetails;
import me.yummykang.entity.tables.OauthClientToken;
import me.yummykang.entity.tables.OauthCode;
import me.yummykang.entity.tables.OauthRefreshToken;
import me.yummykang.entity.tables.SchemaVersion;
import me.yummykang.entity.tables.Users;


/**
 * Convenience access to all tables in workkits
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>workkits.check_in</code>.
     */
    public static final CheckIn CHECK_IN = me.yummykang.entity.tables.CheckIn.CHECK_IN;

    /**
     * The table <code>workkits.oauth_access_token</code>.
     */
    public static final OauthAccessToken OAUTH_ACCESS_TOKEN = me.yummykang.entity.tables.OauthAccessToken.OAUTH_ACCESS_TOKEN;

    /**
     * The table <code>workkits.oauth_client_details</code>.
     */
    public static final OauthClientDetails OAUTH_CLIENT_DETAILS = me.yummykang.entity.tables.OauthClientDetails.OAUTH_CLIENT_DETAILS;

    /**
     * The table <code>workkits.oauth_client_token</code>.
     */
    public static final OauthClientToken OAUTH_CLIENT_TOKEN = me.yummykang.entity.tables.OauthClientToken.OAUTH_CLIENT_TOKEN;

    /**
     * The table <code>workkits.oauth_code</code>.
     */
    public static final OauthCode OAUTH_CODE = me.yummykang.entity.tables.OauthCode.OAUTH_CODE;

    /**
     * The table <code>workkits.oauth_refresh_token</code>.
     */
    public static final OauthRefreshToken OAUTH_REFRESH_TOKEN = me.yummykang.entity.tables.OauthRefreshToken.OAUTH_REFRESH_TOKEN;

    /**
     * The table <code>workkits.schema_version</code>.
     */
    public static final SchemaVersion SCHEMA_VERSION = me.yummykang.entity.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>workkits.users</code>.
     */
    public static final Users USERS = me.yummykang.entity.tables.Users.USERS;
}
