/*
 * This file is generated by jOOQ.
*/
package me.yummykang.entity;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import me.yummykang.entity.tables.CheckIn;
import me.yummykang.entity.tables.OauthAccessToken;
import me.yummykang.entity.tables.OauthClientDetails;
import me.yummykang.entity.tables.OauthClientToken;
import me.yummykang.entity.tables.OauthCode;
import me.yummykang.entity.tables.OauthRefreshToken;
import me.yummykang.entity.tables.SchemaVersion;
import me.yummykang.entity.tables.Users;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Workkits extends SchemaImpl {

    private static final long serialVersionUID = 1480578568;

    /**
     * The reference instance of <code>workkits</code>
     */
    public static final Workkits WORKKITS = new Workkits();

    /**
     * The table <code>workkits.check_in</code>.
     */
    public final CheckIn CHECK_IN = me.yummykang.entity.tables.CheckIn.CHECK_IN;

    /**
     * The table <code>workkits.oauth_access_token</code>.
     */
    public final OauthAccessToken OAUTH_ACCESS_TOKEN = me.yummykang.entity.tables.OauthAccessToken.OAUTH_ACCESS_TOKEN;

    /**
     * The table <code>workkits.oauth_client_details</code>.
     */
    public final OauthClientDetails OAUTH_CLIENT_DETAILS = me.yummykang.entity.tables.OauthClientDetails.OAUTH_CLIENT_DETAILS;

    /**
     * The table <code>workkits.oauth_client_token</code>.
     */
    public final OauthClientToken OAUTH_CLIENT_TOKEN = me.yummykang.entity.tables.OauthClientToken.OAUTH_CLIENT_TOKEN;

    /**
     * The table <code>workkits.oauth_code</code>.
     */
    public final OauthCode OAUTH_CODE = me.yummykang.entity.tables.OauthCode.OAUTH_CODE;

    /**
     * The table <code>workkits.oauth_refresh_token</code>.
     */
    public final OauthRefreshToken OAUTH_REFRESH_TOKEN = me.yummykang.entity.tables.OauthRefreshToken.OAUTH_REFRESH_TOKEN;

    /**
     * The table <code>workkits.schema_version</code>.
     */
    public final SchemaVersion SCHEMA_VERSION = me.yummykang.entity.tables.SchemaVersion.SCHEMA_VERSION;

    /**
     * The table <code>workkits.users</code>.
     */
    public final Users USERS = me.yummykang.entity.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Workkits() {
        super("workkits", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            CheckIn.CHECK_IN,
            OauthAccessToken.OAUTH_ACCESS_TOKEN,
            OauthClientDetails.OAUTH_CLIENT_DETAILS,
            OauthClientToken.OAUTH_CLIENT_TOKEN,
            OauthCode.OAUTH_CODE,
            OauthRefreshToken.OAUTH_REFRESH_TOKEN,
            SchemaVersion.SCHEMA_VERSION,
            Users.USERS);
    }
}
