/*
 * This file is generated by jOOQ.
*/
package me.yummykang.entity.tables.daos;


import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import me.yummykang.entity.tables.CheckIn;
import me.yummykang.entity.tables.records.CheckInRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class CheckInDao extends DAOImpl<CheckInRecord, me.yummykang.entity.tables.pojos.CheckIn, Integer> {

    /**
     * Create a new CheckInDao without any configuration
     */
    public CheckInDao() {
        super(CheckIn.CHECK_IN, me.yummykang.entity.tables.pojos.CheckIn.class);
    }

    /**
     * Create a new CheckInDao with an attached configuration
     */
    @Autowired
    public CheckInDao(Configuration configuration) {
        super(CheckIn.CHECK_IN, me.yummykang.entity.tables.pojos.CheckIn.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(me.yummykang.entity.tables.pojos.CheckIn object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<me.yummykang.entity.tables.pojos.CheckIn> fetchById(Integer... values) {
        return fetch(CheckIn.CHECK_IN.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public me.yummykang.entity.tables.pojos.CheckIn fetchOneById(Integer value) {
        return fetchOne(CheckIn.CHECK_IN.ID, value);
    }

    /**
     * Fetch records that have <code>check_in_time IN (values)</code>
     */
    public List<me.yummykang.entity.tables.pojos.CheckIn> fetchByCheckInTime(Date... values) {
        return fetch(CheckIn.CHECK_IN.CHECK_IN_TIME, values);
    }

    /**
     * Fetch records that have <code>check_out_time IN (values)</code>
     */
    public List<me.yummykang.entity.tables.pojos.CheckIn> fetchByCheckOutTime(Date... values) {
        return fetch(CheckIn.CHECK_IN.CHECK_OUT_TIME, values);
    }

    /**
     * Fetch records that have <code>left_time IN (values)</code>
     */
    public List<me.yummykang.entity.tables.pojos.CheckIn> fetchByLeftTime(Integer... values) {
        return fetch(CheckIn.CHECK_IN.LEFT_TIME, values);
    }
}
