/*
 * This file is generated by jOOQ.
*/
package me.yummykang.entity.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import me.yummykang.entity.tables.Users;
import me.yummykang.entity.tables.records.UsersRecord;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UsersDao extends DAOImpl<UsersRecord, me.yummykang.entity.tables.pojos.Users, Integer> {

    /**
     * Create a new UsersDao without any configuration
     */
    public UsersDao() {
        super(Users.USERS, me.yummykang.entity.tables.pojos.Users.class);
    }

    /**
     * Create a new UsersDao with an attached configuration
     */
    @Autowired
    public UsersDao(Configuration configuration) {
        super(Users.USERS, me.yummykang.entity.tables.pojos.Users.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(me.yummykang.entity.tables.pojos.Users object) {
        return object.getUserId();
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<me.yummykang.entity.tables.pojos.Users> fetchByUserId(Integer... values) {
        return fetch(Users.USERS.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public me.yummykang.entity.tables.pojos.Users fetchOneByUserId(Integer value) {
        return fetchOne(Users.USERS.USER_ID, value);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<me.yummykang.entity.tables.pojos.Users> fetchByUsername(String... values) {
        return fetch(Users.USERS.USERNAME, values);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<me.yummykang.entity.tables.pojos.Users> fetchByPassword(String... values) {
        return fetch(Users.USERS.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>enabled IN (values)</code>
     */
    public List<me.yummykang.entity.tables.pojos.Users> fetchByEnabled(Integer... values) {
        return fetch(Users.USERS.ENABLED, values);
    }
}
